# Generated by Django 4.2.7 on 2025-12-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MapGISCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cbml",
                    models.CharField(
                        db_index=True,
                        help_text="Código Base de Manzana Lote (11 dígitos para MapGIS Medellín)",
                        max_length=11,
                        unique=True,
                        verbose_name="CBML",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Información completa del lote desde MapGIS",
                        verbose_name="Datos",
                    ),
                ),
                (
                    "consulted_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Consulta"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        help_text="Fecha en que expira el cache (24 horas por defecto)",
                        verbose_name="Fecha de Expiración",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False si el cache debe invalidarse",
                        verbose_name="¿Es Válido?",
                    ),
                ),
                (
                    "hit_count",
                    models.IntegerField(
                        default=0,
                        help_text="Cuántas veces se ha usado este cache",
                        verbose_name="Número de Hits",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache MapGIS",
                "verbose_name_plural": "Cache MapGIS",
                "db_table": "mapgis_cache",
                "ordering": ["-consulted_at"],
                "indexes": [
                    models.Index(
                        fields=["cbml", "is_valid"], name="mapgis_cach_cbml_idx"
                    ),
                    models.Index(fields=["expiry_date"], name="mapgis_cach_expiry_idx"),
                    models.Index(
                        fields=["consulted_at"], name="mapgis_cach_consult_idx"
                    ),
                ],
            },
        ),
    ]
