# Generated by Django 4.2.7 on 2025-12-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_05b4bc_idx",
            old_name="notificatio_user_id_1234ab",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_427e4b_idx",
            old_name="notificatio_user_id_5678cd",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_type_36f2e6_idx",
            old_name="notificatio_type_9012ef",
        ),
    ]
