# Generated by Django 4.2.7 on 2025-12-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0002_rename_notificatio_user_id_1234ab_notificatio_user_id_05b4bc_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("lote_aprobado", "Lote Aprobado"),
                    ("lote_rechazado", "Lote Rechazado"),
                    ("documento_validado", "Documento Validado"),
                    ("solicitud_respondida", "Solicitud Respondida"),
                    ("lote_recomendado", "Lote Recomendado"),
                    ("mensaje", "Mensaje"),
                    ("sistema", "Sistema"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="Tipo",
            ),
        ),
    ]
