# Generated by Django 4.2.7 on 2025-12-01 16:53

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código de 6 dígitos",
                        max_length=6,
                        verbose_name="Código",
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Código",
                    ),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="Usado")),
                ("expires_at", models.DateTimeField(verbose_name="Expira en")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Usado en"
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de Verificación",
                "verbose_name_plural": "Códigos de Verificación",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_usernam_65d164_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company_nit",
        ),
        migrations.RemoveField(
            model_name="user",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="deletion_reason",
        ),
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
        migrations.RemoveField(
            model_name="user",
            name="experience_years",
        ),
        migrations.RemoveField(
            model_name="user",
            name="focus_area",
        ),
        migrations.RemoveField(
            model_name="user",
            name="id_verification_file",
        ),
        migrations.RemoveField(
            model_name="user",
            name="lots_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="permissions_scope",
        ),
        migrations.RemoveField(
            model_name="user",
            name="portfolio_url",
        ),
        migrations.RemoveField(
            model_name="user",
            name="position",
        ),
        migrations.AddField(
            model_name="user",
            name="ciudades_interes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de ciudades de interés: ['Medellín', 'Bogotá']",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="developer_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("constructora", "Constructora"),
                    ("fondo_inversion", "Fondo de Inversión"),
                    ("inversionista", "Inversionista"),
                    ("otro", "Otro"),
                ],
                help_text="Tipo de desarrollador",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Email Verificado En"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_login_completed",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el usuario ha completado su primera sesión y visto el mensaje de bienvenida",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_phone_verified",
            field=models.BooleanField(
                default=False, verbose_name="Teléfono Verificado"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="legal_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre completo si es natural, Nombre de empresa si es jurídica",
                max_length=255,
                null=True,
                verbose_name="Nombre Legal/Empresa",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="modelos_pago",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Modelos de pago: ['contado', 'aporte', 'hitos']",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="perfil_completo",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el perfil de inversión está completo",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="person_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("natural", "Persona Natural"),
                    ("juridica", "Persona Jurídica"),
                ],
                help_text="Natural o Jurídica",
                max_length=10,
                null=True,
                verbose_name="Tipo de Persona",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Teléfono Verificado En"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ticket_inversion_min",
            field=models.CharField(
                blank=True,
                choices=[
                    ("menos_150", "< 150.000.000.000"),
                    ("entre_150_350", "Entre 150.000.000.000 y 350.000.000.000"),
                    ("mas_350", "Más de 350.000.000.000"),
                ],
                help_text="Ticket mínimo de inversión (solo para fondos e inversionistas)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="usos_preferidos",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Usos de suelo preferidos: ['residencial', 'comercial', 'industrial', 'logistico']",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="volumen_ventas_min",
            field=models.CharField(
                blank=True,
                choices=[
                    ("menos_150", "< 150.000.000.000"),
                    ("entre_150_350", "Entre 150.000.000.000 y 350.000.000.000"),
                    ("mas_350", "Más de 350.000.000.000"),
                ],
                help_text="Volumen mínimo de ventas esperado",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
        ),
        migrations.AlterField(
            model_name="user",
            name="document_number",
            field=models.CharField(
                blank=True,
                help_text="Solo números",
                max_length=50,
                null=True,
                verbose_name="Número de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CC", "Cédula de Ciudadanía"),
                    ("NIT", "NIT"),
                    ("CE", "Cédula de Extranjería"),
                    ("PASSPORT", "Pasaporte"),
                    ("TI", "Tarjeta de Identidad"),
                ],
                max_length=10,
                null=True,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("owner", "Property Owner"),
                    ("developer", "Developer"),
                ],
                default="owner",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
        migrations.AddField(
            model_name="verificationcode",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_codes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(
                fields=["user", "code_type", "is_used"],
                name="users_verif_user_id_84933c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(
                fields=["code", "expires_at"], name="users_verif_code_888089_idx"
            ),
        ),
    ]
