# Generated by Django 4.2.7 on 2025-12-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_verificationcode_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_role_36d76d_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="user_email_idx",
            old_name="users_user_email_6f2530_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="user_created_at_idx",
            old_name="users_user_created_cf865c_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="ciudades_interes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de ciudades de interés (para desarrolladores)",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "is_active"], name="user_role_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_verified"], name="user_verified_idx"),
        ),
    ]
