# Generated by Django 4.2.7 on 2025-09-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_request_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Dirección de Residencia"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Nombre de la Empresa",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="company_nit",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="NIT de la Empresa"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("normativa", "Normativa"),
                    ("soporte_tecnico", "Soporte Técnico"),
                    ("gestion_usuarios", "Gestión de Usuarios"),
                    ("desarrollo", "Desarrollo"),
                    ("comercial", "Comercial"),
                    ("legal", "Legal"),
                    ("general", "General"),
                ],
                max_length=100,
                null=True,
                verbose_name="Departamento",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="document_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Número de Documento"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CC", "Cédula de Ciudadanía"),
                    ("NIT", "NIT"),
                    ("CE", "Cédula de Extranjería"),
                    ("PASSPORT", "Pasaporte"),
                    ("TI", "Tarjeta de Identidad"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="experience_years",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Años de Experiencia"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="focus_area",
            field=models.CharField(
                blank=True,
                choices=[
                    ("residential", "Residencial"),
                    ("commercial", "Comercial"),
                    ("mixed", "Mixto"),
                    ("vis", "VIS (Vivienda de Interés Social)"),
                    ("industrial", "Industrial"),
                    ("other", "Otro"),
                ],
                max_length=50,
                null=True,
                verbose_name="Área de Enfoque",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="id_verification_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/id_verification/",
                verbose_name="Archivo de Verificación de Identidad",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="lots_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Cantidad de Lotes"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="permissions_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full", "Administrador Completo"),
                    ("limited", "Administrador Limitado"),
                    ("readonly", "Solo Lectura"),
                    ("department", "Solo Departamento"),
                ],
                default="limited",
                max_length=20,
                null=True,
                verbose_name="Alcance de Permisos",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="portfolio_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL del Portafolio"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Cargo"
            ),
        ),
    ]
