# Generated by Django 4.2.7 on 2025-12-01 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lotes", "0004_remove_lote_lotes_owner_i_a10829_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalisisUrbanistico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_analisis",
                    models.CharField(
                        choices=[
                            ("maximo_potencial", "Máximo Potencial"),
                            ("factibilidad", "Factibilidad"),
                            ("normativa", "Análisis Normativo"),
                            ("financiero", "Análisis Financiero"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Tipo de Análisis",
                    ),
                ),
                (
                    "incluir_vis",
                    models.BooleanField(default=False, verbose_name="Incluir VIS"),
                ),
                (
                    "comentarios_solicitante",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Comentarios del Solicitante",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_proceso", "En Proceso"),
                            ("completado", "Completado"),
                            ("rechazado", "Rechazado"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "resultados",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Contiene los datos calculados del análisis",
                        verbose_name="Resultados del Análisis",
                    ),
                ),
                (
                    "observaciones_analista",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones del Analista"
                    ),
                ),
                (
                    "archivo_informe",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="analisis/informes/",
                        verbose_name="Archivo del Informe",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Solicitud"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "fecha_inicio_proceso",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Inicio Proceso"
                    ),
                ),
                (
                    "fecha_completado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Completado"
                    ),
                ),
                (
                    "metadatos",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos Adicionales"
                    ),
                ),
                (
                    "analista",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analisis_realizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Analista Asignado",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analisis",
                        to="lotes.lote",
                        verbose_name="Lote",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analisis_solicitados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis Urbanístico",
                "verbose_name_plural": "Análisis Urbanísticos",
                "db_table": "analisis_urbanistico",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParametroUrbanistico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("area_minima", "Área Mínima Construida"),
                            ("indices", "Índices Urbanísticos"),
                            ("retiros", "Retiros"),
                            ("alturas", "Alturas Máximas"),
                            ("estacionamientos", "Estacionamientos"),
                            ("cesiones", "Cesiones Obligatorias"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Parámetro"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción completa del parámetro para la IA",
                        verbose_name="Descripción Detallada",
                    ),
                ),
                (
                    "datos",
                    models.JSONField(
                        default=dict,
                        help_text="Estructura JSON con los valores del parámetro",
                        verbose_name="Datos del Parámetro",
                    ),
                ),
                (
                    "articulo_pot",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Artículo POT",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("orden", models.IntegerField(default=0, verbose_name="Orden")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Parámetro Urbanístico",
                "verbose_name_plural": "Parámetros Urbanísticos",
                "db_table": "analisis_parametro_urbanistico",
                "ordering": ["categoria", "orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="RespuestaIA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prompt", models.TextField(verbose_name="Prompt Enviado")),
                ("respuesta", models.TextField(verbose_name="Respuesta de la IA")),
                (
                    "modelo_ia",
                    models.CharField(
                        default="gemini-pro",
                        max_length=100,
                        verbose_name="Modelo de IA",
                    ),
                ),
                (
                    "tokens_usados",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tokens Usados"
                    ),
                ),
                (
                    "tiempo_respuesta",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Tiempo de Respuesta (segundos)",
                    ),
                ),
                (
                    "aprobado",
                    models.BooleanField(
                        default=False, verbose_name="Aprobado por Admin"
                    ),
                ),
                (
                    "notas_revision",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas de Revisión"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analisis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas_ia",
                        to="analisis.analisisurbanistico",
                        verbose_name="Análisis",
                    ),
                ),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="respuestas_ia_revisadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisado Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta IA",
                "verbose_name_plural": "Respuestas IA",
                "db_table": "analisis_respuesta_ia",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="analisisurbanistico",
            index=models.Index(
                fields=["lote", "-created_at"], name="analisis_ur_lote_id_19913d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analisisurbanistico",
            index=models.Index(
                fields=["solicitante", "-created_at"],
                name="analisis_ur_solicit_673342_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analisisurbanistico",
            index=models.Index(
                fields=["estado", "-created_at"], name="analisis_ur_estado_e01de7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analisisurbanistico",
            index=models.Index(
                fields=["tipo_analisis", "estado"],
                name="analisis_ur_tipo_an_ab2305_idx",
            ),
        ),
    ]
