# Generated by Django 4.2.7 on 2025-11-18 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lotes", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("soporte_tecnico", "Soporte Técnico"),
                            ("analisis_urbanistico", "Análisis Urbanístico"),
                            ("consulta_general", "Consulta General"),
                            ("validacion_documentos", "Validación de Documentos"),
                            ("correccion_datos", "Corrección de Datos"),
                            ("acceso", "Solicitud de Acceso"),
                            ("funcionalidad", "Solicitud de Funcionalidad"),
                            ("otro", "Otro"),
                        ],
                        db_index=True,
                        default="consulta_general",
                        max_length=50,
                        verbose_name="Tipo de Solicitud",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_revision", "En Revisión"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("completado", "Completado"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "notas_revision",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas de Revisión"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "resuelta_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Resolución"
                    ),
                ),
                (
                    "metadatos",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos Adicionales"
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes",
                        to="lotes.lote",
                        verbose_name="Lote Relacionado",
                    ),
                ),
                (
                    "revisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_revisadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisor",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud",
                "verbose_name_plural": "Solicitudes",
                "db_table": "solicitudes_solicitud",
                "ordering": ["-prioridad", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "estado"],
                        name="solicitudes_usuario_aaca94_idx",
                    ),
                    models.Index(
                        fields=["tipo", "estado"], name="solicitudes_tipo_0373ae_idx"
                    ),
                    models.Index(
                        fields=["lote", "estado"], name="solicitudes_lote_id_87d904_idx"
                    ),
                    models.Index(
                        fields=["prioridad", "-created_at"],
                        name="solicitudes_priorid_245876_idx",
                    ),
                ],
            },
        ),
    ]
