# Generated by Django 4.2.7 on 2025-11-13 21:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "notas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas Personales"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Agregado"
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorito",
                "verbose_name_plural": "Favoritos",
                "db_table": "lotes_favorite",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre identificativo del lote", max_length=200
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        help_text="Dirección completa del lote", max_length=500
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Área del lote en metros cuadrados",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "cbml",
                    models.CharField(
                        blank=True,
                        help_text="Código CBML del lote",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        blank=True,
                        help_text="Matrícula inmobiliaria",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "codigo_catastral",
                    models.CharField(
                        blank=True,
                        help_text="Código catastral",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del lote",
                        null=True,
                    ),
                ),
                (
                    "barrio",
                    models.CharField(
                        blank=True,
                        help_text="Barrio donde se ubica el lote",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "estrato",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Estrato 1"),
                            (2, "Estrato 2"),
                            (3, "Estrato 3"),
                            (4, "Estrato 4"),
                            (5, "Estrato 5"),
                            (6, "Estrato 6"),
                        ],
                        help_text="Estrato socioeconómico",
                        null=True,
                    ),
                ),
                (
                    "latitud",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Coordenada de latitud",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Coordenada de longitud",
                        max_digits=11,
                        null=True,
                    ),
                ),
                (
                    "clasificacion_suelo",
                    models.CharField(
                        blank=True,
                        help_text="Clasificación del suelo según POT",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "uso_suelo",
                    models.CharField(
                        blank=True,
                        help_text="Uso permitido del suelo",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tratamiento_pot",
                    models.CharField(
                        blank=True,
                        help_text="Tratamiento urbanístico según POT",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente de Revisión"),
                            ("active", "Activo y Verificado"),
                            ("rejected", "Rechazado"),
                            ("archived", "Archivado"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Estado del lote en el sistema",
                        max_length=20,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Si el lote ha sido verificado por un administrador",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Motivo por el cual el lote fue rechazado",
                        null=True,
                        verbose_name="Razón de Rechazo",
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Rechazo"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Verificación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metadatos",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Información adicional en formato JSON",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote",
                "verbose_name_plural": "Lotes",
                "db_table": "lotes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoteDocument",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("escritura", "Escritura Pública"),
                            ("cedula_catastral", "Cédula Catastral"),
                            ("plano", "Plano"),
                            ("foto", "Fotografía"),
                            ("levantamiento", "Levantamiento Topográfico"),
                            ("certificado", "Certificado"),
                            ("otro", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="lotes/documentos/", verbose_name="Archivo"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Subida"
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Lote",
                "verbose_name_plural": "Documentos de Lote",
                "db_table": "lotes_lotedocument",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Tratamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=10, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "indice_ocupacion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Índice de Ocupación",
                    ),
                ),
                (
                    "indice_construccion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Índice de Construcción",
                    ),
                ),
                (
                    "altura_maxima",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Altura Máxima (m)"
                    ),
                ),
                (
                    "retiro_frontal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Retiro Frontal (m)",
                    ),
                ),
                (
                    "retiro_lateral",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Retiro Lateral (m)",
                    ),
                ),
                (
                    "retiro_posterior",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Retiro Posterior (m)",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tratamiento Urbanístico",
                "verbose_name_plural": "Tratamientos Urbanísticos",
                "db_table": "lotes_tratamiento",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="LoteHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "campo_modificado",
                    models.CharField(max_length=100, verbose_name="Campo Modificado"),
                ),
                (
                    "valor_anterior",
                    models.TextField(
                        blank=True, null=True, verbose_name="Valor Anterior"
                    ),
                ),
                (
                    "valor_nuevo",
                    models.TextField(blank=True, null=True, verbose_name="Valor Nuevo"),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "motivo",
                    models.TextField(blank=True, null=True, verbose_name="Motivo"),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="lotes.lote",
                        verbose_name="Lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Lote",
                "verbose_name_plural": "Historiales de Lote",
                "db_table": "lotes_lotehistory",
                "ordering": ["-fecha_modificacion"],
            },
        ),
    ]
