# Generated by Django 4.2.7 on 2025-10-09 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lote",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lotes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario propietario",
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Administrador que verificó el lote",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lotes_verificados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="lote",
            field=models.ForeignKey(
                help_text="Lote marcado como favorito",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favoritos",
                to="lotes.lote",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="usuario",
            field=models.ForeignKey(
                help_text="Usuario que marcó el lote como favorito",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lotes_favoritos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tratamientonormativalote",
            unique_together={("tratamiento", "tipo_vivienda")},
        ),
        migrations.AlterUniqueTogether(
            name="tratamientoareaminimavivienda",
            unique_together={("tratamiento", "tipo_vivienda")},
        ),
        migrations.AddIndex(
            model_name="lote",
            index=models.Index(
                fields=["usuario", "estado"], name="lotes_lote_usuario_408738_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lote",
            index=models.Index(
                fields=["is_verified"], name="lotes_lote_is_veri_e94fb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lote",
            index=models.Index(fields=["cbml"], name="lotes_lote_cbml_e1df01_idx"),
        ),
        migrations.AddIndex(
            model_name="lote",
            index=models.Index(
                fields=["fecha_creacion"], name="lotes_lote_fecha_c_d465ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(
                fields=["usuario", "created_at"], name="lotes_fav_usuario_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(
                fields=["lote", "created_at"], name="lotes_fav_lote_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("usuario", "lote")},
        ),
    ]
