# Generated by Django 4.2.7 on 2025-11-13 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lotes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lotehistory",
            name="modificado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modificaciones_lotes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificado por",
            ),
        ),
        migrations.AddField(
            model_name="lotedocument",
            name="lote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos",
                to="lotes.lote",
                verbose_name="Lote",
            ),
        ),
        migrations.AddField(
            model_name="lotedocument",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_subidos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Subido por",
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="owner",
            field=models.ForeignKey(
                help_text="Propietario del lote",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lotes_owned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lotes_rejected",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Rechazado por",
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lotes_verified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Verificado por",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="lote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favoritos",
                to="lotes.lote",
                verbose_name="Lote",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favoritos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddIndex(
            model_name="lote",
            index=models.Index(
                fields=["owner", "-created_at"], name="lotes_owner_i_a10829_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lote",
            index=models.Index(
                fields=["status", "is_verified"], name="lotes_status_5744ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lote",
            index=models.Index(fields=["cbml"], name="lotes_cbml_27bf76_idx"),
        ),
        migrations.AddIndex(
            model_name="lote",
            index=models.Index(fields=["matricula"], name="lotes_matricu_e3cefc_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "lote")},
        ),
    ]
