# Generated by Django 4.2.7 on 2025-09-01 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0002_add_new_lote_fields'),
        ('lotes', '0002_documentos_requeridos'),
    ]

    operations = [
    ]
