# Generated by Django 4.2.7 on 2025-10-07 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lotes", "0002_add_verification_and_favorites"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="favorite",
            new_name="lotes_favor_usuario_1cbe49_idx",
            old_name="lotes_fav_usuario_idx",
        ),
        migrations.RenameIndex(
            model_name="favorite",
            new_name="lotes_favor_lote_id_726148_idx",
            old_name="lotes_fav_lote_idx",
        ),
    ]
