# Generated by Django 4.2.7 on 2025-12-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotehistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Creado"),
                    ("updated", "Actualizado"),
                    ("verified", "Verificado"),
                    ("rejected", "Rechazado"),
                    ("deleted", "Eliminado"),
                ],
                default="updated",
                max_length=20,
                verbose_name="Acción",
            ),
        ),
        migrations.AlterField(
            model_name="lotehistory",
            name="campo_modificado",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Campo Modificado"
            ),
        ),
    ]
