# Generated by Django 4.2.7 on 2025-12-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotes", "0003_lotehistory_action_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="lote",
            name="lotes_owner_i_a10829_idx",
        ),
        migrations.RemoveIndex(
            model_name="lote",
            name="lotes_matricu_e3cefc_idx",
        ),
        migrations.RenameIndex(
            model_name="lote",
            new_name="lote_status_verified_idx",
            old_name="lotes_status_5744ba_idx",
        ),
        migrations.RenameIndex(
            model_name="lote",
            new_name="lote_cbml_idx",
            old_name="lotes_cbml_27bf76_idx",
        ),
        migrations.AddIndex(
            model_name="lote",
            index=models.Index(
                fields=["owner", "status"], name="lote_owner_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lote",
            index=models.Index(fields=["created_at"], name="lote_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="lote",
            index=models.Index(fields=["uso_suelo"], name="lote_uso_suelo_idx"),
        ),
        migrations.AddIndex(
            model_name="lote",
            index=models.Index(fields=["tratamiento_pot"], name="lote_tratamiento_idx"),
        ),
    ]
