# Generated by Django 4.2.7 on 2025-09-08 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0004_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='estrato',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Estrato socioeconómico (1-6)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Estrato'),
        ),
    ]
