# Generated by Django 4.2.7 on 2025-12-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lotes", "0003_add_missing_fields"),
        ("lotes", "0004_remove_lote_lotes_owner_i_a10829_idx_and_more"),
    ]

    operations = []
