# Generated by Django 4.2.7 on 2025-12-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotes", "0005_merge_20251202_1503"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lote",
            name="carta_autorizacion",
            field=models.FileField(
                blank=True,
                help_text="Carta de autorización del propietario (requerida si es comisionista)",
                null=True,
                upload_to="lotes/autorizaciones/",
                verbose_name="Carta de Autorización",
            ),
        ),
        migrations.AlterField(
            model_name="lote",
            name="ciudad",
            field=models.CharField(
                blank=True,
                help_text="Ciudad donde se ubica el lote",
                max_length=100,
                null=True,
                verbose_name="Ciudad",
            ),
        ),
        migrations.AlterField(
            model_name="lote",
            name="es_comisionista",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el registro lo hace un comisionista en representación del propietario",
                verbose_name="Es Comisionista",
            ),
        ),
        migrations.AlterField(
            model_name="lote",
            name="forma_pago",
            field=models.CharField(
                blank=True,
                choices=[
                    ("contado", "De Contado"),
                    ("financiado", "Financiado"),
                    ("permuta", "Permuta"),
                    ("mixto", "Mixto"),
                ],
                help_text="Forma de pago preferida para la transacción",
                max_length=20,
                null=True,
                verbose_name="Forma de Pago",
            ),
        ),
        migrations.AlterField(
            model_name="lote",
            name="valor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor comercial del lote en COP",
                max_digits=15,
                null=True,
                verbose_name="Valor del Lote",
            ),
        ),
    ]
