# Generated by Django - Modified to run AFTER data truncation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotes", "0008_truncate_cbml_to_11"),  # ✅ CRÍTICO: Ahora depende de 0008
    ]

    operations = [
        migrations.AlterField(
            model_name="lote",
            name="cbml",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código de identificación catastral (CBML) - 11 dígitos para MapGIS Medellín",
                max_length=11,
                null=True,
                unique=True,
                verbose_name="CBML",
            ),
        ),
    ]
