# Generated by Django 4.2.7 on 2025-12-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lotes", "0007_alter_lote_cbml"),
        ("lotes", "0009_truncate_cbml_to_11"),
    ]

    operations = []
