# Generated by Django 4.2.7 on 2025-12-03 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotes", "0010_merge_0007_alter_lote_cbml_0009_truncate_cbml_to_11"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lote",
            name="cbml",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código de identificación catastral (CBML) - 11 dígitos para MapGIS Medellín",
                max_length=11,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_cbml",
                        message="El CBML debe tener exactamente 11 dígitos numéricos",
                        regex="^\\d{11}$",
                    )
                ],
                verbose_name="CBML",
            ),
        ),
    ]
