# Generated by Django 4.2.7 on 2025-12-04 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lotes", "0011_alter_lote_cbml"),
    ]

    operations = [
        migrations.AddField(
            model_name="lote",
            name="desarrolladores",
            field=models.ManyToManyField(
                blank=True,
                help_text="Desarrolladores que tienen acceso a este lote",
                limit_choices_to={"role": "developer"},
                related_name="lotes_as_developer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Desarrolladores Autorizados",
            ),
        ),
    ]
