# Generated by Django 4.2.7 on 2025-10-09 15:22

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Fecha")),
                ("metrics", models.JSONField(default=dict, verbose_name="Métricas")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Resumen Diario",
                "verbose_name_plural": "Resúmenes Diarios",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("view", "Vista"),
                            ("search", "Búsqueda"),
                            ("action", "Acción"),
                            ("api", "API"),
                            ("error", "Error"),
                            ("other", "Otro"),
                        ],
                        default="other",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("event_name", models.CharField(blank=True, max_length=255, null=True)),
                ("event_value", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("user_agent", models.TextField(blank=True, default="")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Estadística",
                "verbose_name_plural": "Estadísticas",
                "ordering": ["-timestamp"],
            },
        ),
    ]
