# Generated by Django 4.2.7 on 2025-10-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Fecha")),
                ("metrics", models.JSONField(default=dict, verbose_name="Métricas")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Resumen Diario",
                "verbose_name_plural": "Resúmenes Diarios",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("view", "Vista de página"),
                            ("search", "Búsqueda"),
                            ("action", "Acción de usuario"),
                            ("api", "Llamada a API"),
                            ("error", "Error"),
                            ("other", "Otro"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Nombre"
                    ),
                ),
                (
                    "value",
                    models.JSONField(blank=True, default=dict, verbose_name="Valor"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Marca de tiempo"
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="ID de Usuario",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID de Sesión",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
            ],
            options={
                "verbose_name": "Estadística",
                "verbose_name_plural": "Estadísticas",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["type", "timestamp"], name="stats_stat_type_32e6a8_idx"
                    ),
                    models.Index(
                        fields=["name", "timestamp"], name="stats_stat_name_f0f0d3_idx"
                    ),
                    models.Index(
                        fields=["user_id", "timestamp"],
                        name="stats_stat_user_id_c76066_idx",
                    ),
                ],
            },
        ),
    ]
