# Generated by Django 4.2.7 on 2025-10-09 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stat",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="stat",
            index=models.Index(
                fields=["-timestamp"], name="stats_stat_timesta_73182a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stat",
            index=models.Index(
                fields=["user", "-timestamp"], name="stats_stat_user_id_67f0cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stat",
            index=models.Index(
                fields=["event_type", "-timestamp"],
                name="stats_stat_event_t_9c8dae_idx",
            ),
        ),
    ]
