# Generated by Django 4.2.7 on 2025-09-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_stat_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stat',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID de Sesión'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Marca de tiempo'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='type',
            field=models.CharField(choices=[('view', 'Vista de página'), ('search', 'Búsqueda'), ('action', 'Acción de usuario'), ('api', 'Llamada a API'), ('error', 'Error'), ('other', 'Otro')], db_index=True, max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID de Usuario'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='value',
            field=models.JSONField(blank=True, default=dict, verbose_name='Valor'),
        ),
        migrations.AddIndex(
            model_name='stat',
            index=models.Index(fields=['type', 'timestamp'], name='stats_stat_type_32e6a8_idx'),
        ),
        migrations.AddIndex(
            model_name='stat',
            index=models.Index(fields=['name', 'timestamp'], name='stats_stat_name_f0f0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='stat',
            index=models.Index(fields=['user_id', 'timestamp'], name='stats_stat_user_id_c76066_idx'),
        ),
    ]
