# Generated by Django 4.2.7 on 2025-09-01 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Fecha")),
                ("metrics", models.JSONField(default=dict, verbose_name="Métricas")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Resumen Diario",
                "verbose_name_plural": "Resúmenes Diarios",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("view", "Vista de página"),
                            ("search", "Búsqueda"),
                            ("action", "Acción de usuario"),
                            ("api", "Llamada a API"),
                            ("error", "Error"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("value", models.JSONField(default=dict, verbose_name="Valor")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Marca de tiempo",
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID de Usuario"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID de Sesión",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
            ],
            options={
                "verbose_name": "Estadística",
                "verbose_name_plural": "Estadísticas",
                "ordering": ["-timestamp"],
            },
        ),
    ]
