# Generated by Django 4.2.7 on 2025-11-13 21:17

import apps.documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lotes", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Título del documento (se genera automáticamente si no se proporciona)",
                        max_length=255,
                        verbose_name="Título",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Archivo del documento (máx. 10MB)",
                        upload_to=apps.documents.models.document_upload_path,
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ctl", "Certificado de Tradición y Libertad"),
                            ("planos", "Planos Arquitectónicos"),
                            ("topografia", "Levantamiento Topográfico"),
                            ("licencia_construccion", "Licencia de Construcción"),
                            ("escritura_publica", "Escritura Pública"),
                            ("certificado_libertad", "Certificado de Libertad"),
                            ("avaluo_comercial", "Avalúo Comercial"),
                            ("estudio_suelos", "Estudio de Suelos"),
                            ("otros", "Otros Documentos"),
                        ],
                        db_index=True,
                        default="otros",
                        max_length=50,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tamaño (bytes)"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Tipo MIME"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Etiquetas"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Validación"
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="lotes.lote",
                        verbose_name="Lote",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_validated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "db_table": "documents_document",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="documents_d_user_id_a8f8c0_idx",
                    ),
                    models.Index(
                        fields=["lote", "-created_at"],
                        name="documents_d_lote_id_7b88cf_idx",
                    ),
                    models.Index(
                        fields=["document_type", "is_active"],
                        name="documents_d_documen_c85bf6_idx",
                    ),
                ],
            },
        ),
    ]
