# Generated by Django 4.2.7 on 2025-10-27 06:08

import apps.documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='documents_user_id_2e6f61_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='documents_lote_id_30f5c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='documents_documen_93e53b_idx',
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('general', 'General'), ('plano', 'Plano'), ('contrato', 'Contrato'), ('licencia', 'Licencia'), ('factura', 'Factura'), ('otro', 'Otro')], default='general', max_length=50, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=apps.documents.models.document_upload_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Tamaño del archivo (bytes)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lotes.lote'),
        ),
        migrations.AlterField(
            model_name='document',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadatos adicionales'),
        ),
        migrations.AlterField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo MIME'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='document',
            table=None,
        ),
    ]
