# Generated by Django 4.2.7 on 2025-10-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_documents_user_id_2e6f61_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('ctl', 'Certificado de Tradición y Libertad'), ('planos', 'Planos Arquitectónicos'), ('topografia', 'Levantamiento Topográfico'), ('licencia_construccion', 'Licencia de Construcción'), ('escritura_publica', 'Escritura Pública'), ('certificado_libertad', 'Certificado de Libertad'), ('avaluo_comercial', 'Avalúo Comercial'), ('estudio_suelos', 'Estudio de Suelos'), ('otros', 'Otros Documentos')], default='otros', max_length=50, verbose_name='Tipo de documento'),
        ),
    ]
