# Generated by Django 4.2.7 on 2025-09-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_validation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='estado_validacion',
        ),
        migrations.RemoveField(
            model_name='document',
            name='validacion_comentarios',
        ),
        migrations.RemoveField(
            model_name='document',
            name='validacion_fecha',
        ),
    ]
