# Generated by Django 5.0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cbml', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('direccion', models.TextField()),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('matricula', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('codigo_catastral', models.CharField(blank=True, max_length=100, null=True)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('estrato', models.IntegerField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('tratamiento_pot', models.CharField(blank=True, max_length=100, null=True)),
                ('uso_suelo', models.CharField(blank=True, max_length=200, null=True)),
                ('clasificacion_suelo', models.CharField(blank=True, max_length=100, null=True)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente de Revisión'), ('active', 'Activo'), ('archived', 'Archivado'), ('rejected', 'Rechazado')], default='pending', help_text='Estado actual del lote', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Indica si el lote ha sido verificado por un administrador')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Fecha y hora de verificación', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Razón de rechazo si el estado es rejected', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Administrador que verificó el lote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_verificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'lotes_lote',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['usuario', 'estado'], name='lotes_lote_usuario_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['is_verified'], name='lotes_lote_is_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['cbml'], name='lotes_lote_cbml_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['matricula'], name='lotes_lote_matricula_idx'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, help_text='Notas personales sobre el lote', null=True)),
                ('lote', models.ForeignKey(help_text='Lote marcado como favorito', on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='lotes.lote')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que marcó el lote como favorito', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote Favorito',
                'verbose_name_plural': 'Lotes Favoritos',
                'db_table': 'lotes_favoritos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['usuario', 'created_at'], name='lotes_fav_usuario_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['lote', 'created_at'], name='lotes_fav_lote_idx'),
        ),
    ]
