# Generated by Django 4.2.7 on 2025-11-18 16:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lotes", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentCriteria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo para identificar este criterio",
                        max_length=200,
                        verbose_name="Nombre del Criterio",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del criterio",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "area_min",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Área mínima del lote en metros cuadrados",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Área Mínima (m²)",
                    ),
                ),
                (
                    "area_max",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Área máxima del lote en metros cuadrados",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Área Máxima (m²)",
                    ),
                ),
                (
                    "budget_min",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Presupuesto mínimo de inversión",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Presupuesto Mínimo (COP)",
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Presupuesto máximo de inversión",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Presupuesto Máximo (COP)",
                    ),
                ),
                (
                    "zones",
                    models.JSONField(
                        default=list,
                        help_text="Lista de zonas o barrios de interés",
                        verbose_name="Zonas de Interés",
                    ),
                ),
                (
                    "treatments",
                    models.JSONField(
                        default=list,
                        help_text="Lista de tratamientos urbanísticos preferidos",
                        verbose_name="Tratamientos de Interés",
                    ),
                ),
                (
                    "estratos",
                    models.JSONField(
                        default=list,
                        help_text="Lista de estratos preferidos",
                        verbose_name="Estratos de Interés",
                    ),
                ),
                (
                    "uso_suelo_preferido",
                    models.JSONField(
                        default=list,
                        help_text="Lista de usos de suelo preferidos (residencial, comercial, etc.)",
                        verbose_name="Usos de Suelo Preferidos",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("inactive", "Inactivo"),
                            ("archived", "Archivado"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "enable_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Recibir notificaciones cuando haya lotes que coincidan",
                        verbose_name="Habilitar Notificaciones",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos Adicionales"
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_criteria",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Desarrollador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Criterio de Inversión",
                "verbose_name_plural": "Criterios de Inversión",
                "db_table": "investment_criteria",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CriteriaMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "match_score",
                    models.IntegerField(
                        default=0,
                        help_text="Puntuación de 0-100 indicando qué tan bien coincide",
                        verbose_name="Puntuación de Coincidencia",
                    ),
                ),
                (
                    "notified",
                    models.BooleanField(
                        default=False,
                        help_text="Si el desarrollador fue notificado sobre este match",
                        verbose_name="Notificado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "criteria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="investment_criteria.investmentcriteria",
                        verbose_name="Criterio",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria_matches",
                        to="lotes.lote",
                        verbose_name="Lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coincidencia de Criterio",
                "verbose_name_plural": "Coincidencias de Criterios",
                "db_table": "investment_criteria_match",
                "ordering": ["-match_score", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="investmentcriteria",
            index=models.Index(
                fields=["developer", "status"], name="investment__develop_492b2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentcriteria",
            index=models.Index(
                fields=["status", "-created_at"], name="investment__status_ae7ab9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="criteriamatch",
            unique_together={("criteria", "lote")},
        ),
    ]
